[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.m3u8"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Content-Type = "application/vnd.apple.mpegurl"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Content-Type = "video/mp2t"

[[headers]]
  for = "/reproductor-appletv.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:; media-src *; connect-src *; frame-src *;"

[[redirects]]
  from = "/stream/*"
  to = "/reproductor-appletv.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 