[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Range"

[[headers]]
  for = "*.m3u8"
  [headers.values]
    Content-Type = "application/vnd.apple.mpegurl"

[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "video/mp2t"
